return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      -- "bash",
      "comment",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "hcl",
      "html",
      "http",
      "ini",
      "javascript",
      "jq",
      "json",
      "json5",
      "just",
      "lua",
      "markdown",
      "markdown_inline",
      "mermaid",
      "org",
      "python",
      "rust",
      "sql",
      "starlark",
      "toml",
      "typescript",
    },
  },
}
