[".config/nvim-profiles/chad/nvim"]
type = "archive"
url = "https://github.com/NvChad/NvChad/archive/refs/heads/main.zip"
stripComponents = 1
refreshPeriod = "168h"

[".config/nvim-profiles/astro/nvim"]
type = "archive"
url = "https://github.com/AstroNvim/AstroNvim/archive/refs/heads/main.zip"
stripComponents = 1
refreshPeriod = "168h"

[".config/alacritty/colors/base16"]
type = "archive"
url = "https://github.com/aarowill/base16-alacritty/archive/refs/heads/master.zip"
include = ['*/colors/*']
stripComponents = 2
refreshPeriod = "168h"

[".config/alacritty/colors/misc"]
type = "archive"
url = "https://github.com/alacritty/alacritty-theme/archive/refs/heads/master.zip"
include = ['*/themes/*']
stripComponents = 2
refreshPeriod = "168h"

[".config/tmux/tmux.conf"]
type = "file"
url = "https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf"
refreshPeriod = "168h"
