# [".config/nvim-profiles/chad/nvim"]
# type = "git-repo"
# url = "https://github.com/NvChad/NvChad"
# refreshPeriod = "168h"
#
# [".config/nvim-profiles/astro/nvim"]
# type = "git-repo"
# url = "https://github.com/AstroNvim/AstroNvim"
# refreshPeriod = "168h"

[".config/alacritty/colors/base16"]
type = "archive"
url = "https://github.com/aarowill/base16-alacritty/archive/refs/heads/master.zip"
include = ['*/colors/*']
stripComponents = 2
refreshPeriod = "168h"

[".config/alacritty/colors/misc"]
type = "archive"
url = "https://github.com/alacritty/alacritty-theme/archive/refs/heads/master.zip"
include = ['*/themes/*']
stripComponents = 2
refreshPeriod = "168h"
