[[colors.indexed_colors]]
color = "0xfa8d3e"
index = 16

[[colors.indexed_colors]]
color = "0xe6ba7e"
index = 17

[[colors.indexed_colors]]
color = "0xf3f4f5"
index = 18

[[colors.indexed_colors]]
color = "0xf8f9fa"
index = 19

[[colors.indexed_colors]]
color = "0x828c99"
index = 20

[[colors.indexed_colors]]
color = "0x242936"
index = 21

[colors.bright]
black = "0xabb0b6"
blue = "0x36a3d9"
cyan = "0x4cbf99"
green = "0x86b300"
magenta = "0xa37acc"
red = "0xf07178"
white = "0x1a1f29"
yellow = "0xf2ae49"

[colors.cursor]
cursor = "0x5c6773"
text = "0xfafafa"

[colors.normal]
black = "0xfafafa"
blue = "0x36a3d9"
cyan = "0x4cbf99"
green = "0x86b300"
magenta = "0xa37acc"
red = "0xf07178"
white = "0x5c6773"
yellow = "0xf2ae49"

[colors.primary]
background = "0xfafafa"
foreground = "0x5c6773"
